package com.bio.GoodVibes;

import com.acher.HaGaon.SendVerse;
import com.jagrosh.jdautilities.command.Command;
import com.jagrosh.jdautilities.command.CommandEvent;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Kongzi extends Command {
    public Kongzi() {
        this.name = "kz";
        this.help = "pulls a teaching from Confucius";
    }

    protected void execute(CommandEvent cmd) {
        int quote = (int) (((System.currentTimeMillis() &0x00FF)) % a.size());

        SendVerse.sendEmbed("in "+b.get(quote)+", Confucius says:", a.get(quote), cmd);
    }

    private List<String> a = Arrays.asList(
            "Of all that Heaven produces and nourishes, there is none so great as man.",
            "Ceremonies are the first thing to be attended to in the practice of government.",
            "From the loving example of one family a whole State may become loving, and from its courtesies, courteous; while from the ambition and perverseness of the one man the whole State may be thrown into rebellious disorder. Such is the nature of influence.",
            "A youth is to be regarded with respect. How do we know that his future will not be equal to our present?",
            "When a country is well governed, poverty and a mean condition are something to be ashamed of. When a country is ill governed, riches and honors are something to be ashamed of.",
            "It cannot be when the root is neglected that what springs from it will be well ordered.",
            "The virtuous will be sure to speak uprightly; but those whose speech is upright may not be virtuous.",
            "Man is born for uprightness. If a man lose his uprightness and yet live, his escape from death is mere good fortune.",
            "The sun and moon shine on all without partiality.",
            "The inner nature of man is the province of music.",
            "There is good government when those who are near are made happy, and when those who are afar are attracted.",
            "The superior man, while his parents are alive, reverently nourishes them; and, when they are dead, reverently sacrifices to them. His thought to the end of his life is how not to disgrace them.",
            "If a man be under the influence of anger his conduct will not be correct.",
            "Sincerity is the way of heaven.",
            "Fine words and an insinuating appearance are seldom associated with virtue.",
            "Virtue is more to a man than either water or fire. I have seen men die from treading on water and fire, but I have never seen a man die from treading the course of virtue.",
            "Virtue is not left to stand alone. He who practices it will have neighbors.",
            "The small man thinks that small acts of goodness are of no benefit, and does not do them; and that small deeds of evil do no harm, and does not refrain from them. Hence, his wickedness becomes so great that it cannot be concealed, and his guilt so great that it cannot be pardoned.",
            "When you have faults, do not fear to abandon them.",
            "Even in killing men, observe the rules of propriety.",
            "By the ruler's cultivation of his own character there is set up the example of the course which all should pursue.",
            "When superiors are fond of showing their humanity, inferiors try to outstrip one another in their practice of it.",
            "The scholar does not consider gold and jade to be precious treasures, but loyalty and good faith.",
            "He who keeps danger in mind will rest safely in his seat.",
            "Have no friends not equal to yourself.",
            "It was by music that the ancient kings gave elegant expression to their joy. By their armies and axes they gave the same to their anger.",
            "Although your father and mother are dead, if you propose to yourself any good work, only reflect how it will make their names illustrious, and your purpose will be fixed.",
            "If I hear the way of truth in the morning, I am content even to die in the evening.",
            "The path may not be left for an instant. If it could be left, it would not be the path.",
            "Recompense injury with justice, and recompense kindness with kindness.",
            "The man who moves a mountain begins by carrying away small stones.",
            "The way of Heaven and Earth may be completely declared in one sentence: They are without any doubleness, and so they produce things in a manner that is unfathomable.",
            "Never give a sword to a man who can't dance.",
            "To study and not think is a waste. To think and not study is dangerous.",
            "Heaven begat Virtue in me; what can man do unto me?",
            "Learn, as if never overtaking your object, and yet as if apprehensive of losing it.",
            "The mechanic that would perfect his work must first sharpen his tools.",
            "The superior man does what is proper to the station in which he is; he does not desire to go beyond this. In a position of wealth and honor, he does what is proper to a position of wealth and honor. In a poor and low position, he does what is proper to a poor and low position. Situated among barbarous tribes, he does what is proper to a situation among barbarous tribes. In a position of sorrow and difficulty, he does what is proper to a position of sorrow and difficulty. The superior man can find himself in no situation in which he is not himself.",
            "When you meet someone better than yourself, turn your thoughts to becoming his equal.",
            "Everything has its beauty, but not everyone sees it.",
            "When the wind blows,the grass bends.",
            "The superior man is modest in his speech, but exceeds in his actions.",
            "To the average man, and those above average, it is possible to discourse on higher subjects; to those from the average downwards, it is not possible.",
            "As I came not into life with any knowledge of it, and as my likings are for what is old, I busy myself in seeking knowledge there.",
            "When I walk along with two others, from at least one I will be able to learn.",
            "Respect yourself and others will respect you.",
            "When one cultivates to the utmost the principles of his nature, and exercises them on the principle of reciprocity, he is not far from the path. What you do not like when done to yourself, do not do to others.",
            "In all things success depends on previous preparation, and without such previous preparation there is sure to be failure.",
            "Not to discuss with a man worthy of conversation is to waste the man. To discuss with a man not worthy of conversation is to waste words. The wise waste neither men nor words.",
            "It is the way of the superior man to prefer the concealment of his virtue, while it daily becomes more illustrious, and it is the way of the mean man to seek notoriety, while he daily goes more and more to ruin.",
            "I am not bothered by the fact that I am not understood. I am bothered when I do not know others.",
            "There is nobody but eats and drinks. But they are few who can distinguish flavors.",
            "If you see what is right and fail to act on it, you lack courage.",
            "They who know the truth are not equal to those who love it, and they who love it are not equal to those who delight in it.",
            "Heaven, in the production of things, is sure to be bountiful to them according to their qualities. Hence the tree that is flourishing, it nourishes, while that which is ready to fall, it overthrows.",
            "The cautious seldom err.",
            "Rarely do we meet with the right feeling due from one man to another where there is fine speech and studied mien.",
            "It is moral cowardice to leave undone what one perceives to be right to do.",
            "If the great man be not grave, he will not be revered.",
            "The great man is many-minded, and not one-sided. The common man is the reverse.",
            "Be versed in ancient lore, and familiarize yourself with the modern; then may you become teachers.",
            "Let a ruler base his government upon virtuous principles, and he will be like the pole-star, which remains steadfast in its place, while all the host of stars turn towards it.",
            "Sincerity is the way of Heaven.",
            "True wisdom is knowing what you don't know.",
            "Care not for being unknown, but seek to be worthy of note.",
            "In archery we have something like the way of the superior man. When the archer misses the center of the target, he turns round and seeks for the cause of his failure in himself.",
            "The superior man acts before he speaks, and afterwards speaks according to his actions.",
            "The way which the superior man pursues, reaches wide and far, and yet is secret. Common men and women, however ignorant, may intermeddle with the knowledge of it; yet in its utmost reaches, there is that which even the sage does not know.",
            "He who exercises government by means of his virtue may be compared to the north polar star, which keeps its place when all the stars are rotating about it.",
            "The superior man, when resting in safety, does not forget that danger may come. When in a state of security he does not forget the possibility of ruin. When all is orderly, he does not forget that disorder may come. Thus his person is not endangered, and his States and all their clans are preserved.",
            "Riches and honor are what men desire; but if they arrive at them by improper ways, they should not continue to hold them. Poverty and low estate are what men dislike; but if they arrive at such a condition by improper ways, they should not refuse it.",
            "Coloring requires a pure and clear background.",
            "Men of loftier mind manifest themselves in their equitable dealings; small-minded men in their going after gain.",
            "The life of a man is--his rectitude. Life without it--such may you have the good fortune to avoid!",
            "It is social good feeling that gives charm to a neighborhood. And where is the wisdom of those who choose an abode where it does not abide?",
            "What you do not want done to yourself, do not do to others.",
            "All things are nourished together without their injuring one another. The courses of the seasons, and of the sun and moon, are pursued without any collision among them. The smaller energies are like river currents; the greater energies are seen in mighty transformations. It is this which makes heaven and earth so great.",
            "If names be not correct, language is not in accordance with the truth of things.",
            "The people may be put into the way they should go, though they may not be put into the way of understanding it.",
            "Some may study side by side, and yet be asunder when they come to the logic of things.",
            "The wise escape doubt; the good-hearted, trouble; the bold, apprehension.",
            "The really faithful lover of learning holds fast to the Good Way till death.",
            "Let there be three men walking together: from that number I should be sure to find my instructors; for what is good in them I should choose out and follow, and what is not good I should modify.",
            "Can any do otherwise than assent to words said to them by way of correction? Only let them reform by such advice, and it will then be reckoned valuable. Can any be other than pleased with words of gentle suasion? Only let them comply with them fully, and such also will be accounted valuable. With those who are pleased without so complying, and those who assent but do not reform, I can do nothing at all.",
            "Not easily found is the man who, after three years' study, has failed to come upon some fruit of his toil.",
            "Take an illustration from the making of a hill. A simple basketful is wanting to complete it, and the work stops. So I stop short.",
            "What the superior man seeks is in himself; what the small man seeks is in others.",
            "If my soul is not engaged in worship, it is even as though I worshipped not.",
            "If one learns from others but does not think, one is still at a loss. If, on the other hand, one thinks but does not learn from others, one is in peril.",
            "Hold faithfulness and sincerity as first principles.",
            "How abundantly do spiritual beings display the powers that belong to them!",
            "Why should man boast of his strength; is not the horse stronger than he?",
            "If you want a man to succeed in the reform of his affairs which are in a deadlock and mess, you must self-evidently first of all tell him how to reform the instrument with which he has to carry out that reform--the instrument, viz, the man himself.",
            "Fear not to reform.",
            "See much and get rid of what is dangerous and be careful in acting on the rest and your causes for regret will be few.",
            "Trying to satisfy one's desires with possessions is like putting out a fire with straw.",
            "He who knows right principles is not equal to him who loves them.",
            "He who wishes to secure the good of others has already secured his own."
    );
    private static List<String> b = Arrays.asList("The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Analects",
            "The Doctrine of the Mean",
            "The Analects",
            "The Analects",
            "The Doctrine of the Mean",
            "The Analects",
            "The Analects",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Analects",
            "The Doctrine of the Mean",
            "The Analects",
            "Sayings of Confucius",
            "The Analects",
            "The Analects",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Analects",
            "Sayings of Confucius",
            "The Doctrine of the Mean",
            "The Doctrine of the Mean",
            "The Analects",
            "The Doctrine of the Mean",
            "The Analects",
            "The Doctrine of the Mean",
            "The Analects",
            "The Analects",
            "The Doctrine of the Mean",
            "The Analects",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Doctrine of the Mean",
            "Sayings of Confucius",
            "Sayings of Confucius",
            "The Doctrine of the Mean",
            "The Analects",
            "The Doctrine of the Mean",
            "The Analects",
            "The Analects",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Analects",
            "The Doctrine of the Mean",
            "The Analects",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "The Wisdom of Confucius",
            "Wisdom of Confucius",
            "attributed, Day's Collacon",
            "The Analects",
            "The Analects",
            "attributed, Day's Collacon",
            "attributed, Day's Collacon",
            "The Universal Order: Or, Conduct of Life, a Confucian Catechism",
            "attributed, Day's Collacon",
            "The Analects",
            "attributed, Treasury of Spiritual Wisdom",
            "attributed, Day's Collacon",
            "attributed, Treasury of Thought"
    );
}